FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy app code + UI
COPY main.py .
COPY templates ./templates
COPY static ./static

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
