apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - name: http
      port: {{ .Values.service.fastapi.port }}
      targetPort: {{ .Values.service.fastapi.port }}
